/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Document Converter
 #	author : miyako
 #	2015/10/02
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

typedef struct
{
	NSData *data;
	NSDictionary *options;
	NSDictionary *attributes;
	NSAttributedString *attributedString;
	NSString *srcDocumentType;
	NSString *dstDocumentType;
} ConverterContext;

void parseDataInMainProcess(ConverterContext *context){

	NSError *error;
	
	context->attributedString = [[NSAttributedString alloc]initWithData:context->data
																options:context->options
													 documentAttributes:NULL
																  error:&error];
}

void parseData(ConverterContext *context, C_BLOB &result){
			
	PA_RunInMainProcess((PA_RunInMainProcessProcPtr)parseDataInMainProcess, (void *)context);

	if(context->attributedString){
		
		NSError *error;
		NSData *data;
		
		if([context->dstDocumentType isEqualToString:NSPlainTextDocumentType]){
		
			data = [[context->attributedString string]dataUsingEncoding:NSUTF8StringEncoding];
			
		}else{
			
			data = [context->attributedString dataFromRange:NSMakeRange(0, [context->attributedString length]) 
										 documentAttributes:context->attributes 
													  error:&error];
		}

		if(data){
			result.setBytes((const uint8_t *)[data bytes], [data length]);
		}	
		
		[context->attributedString release];
	}		
}

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- Document Converter

		case 1 :
			Convert_document(pResult, pParams);
			break;

		case 2 :
			SET_ENVIRONMENT_VARIABLE(pResult, pParams);
			break;

		case 3 :
			Get_environment_variable(pResult, pParams);
			break;

	}
}

// ------------------------------ Document Converter ------------------------------


void Convert_document(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_BLOB Param1;
	C_LONGINT Param2;
	C_LONGINT Param3;
	C_TEXT Param4;
	C_BLOB returnValue;

	Param1.fromParamAtIndex(pParams, 1);
	Param2.fromParamAtIndex(pParams, 2);
	Param3.fromParamAtIndex(pParams, 3);
	Param4.fromParamAtIndex(pParams, 4);

	ConverterContext context;

	context.data = [[NSData alloc]initWithBytes:Param1.getBytesPtr() length:Param1.getBytesLength()];	

	switch (Param2.getIntValue()) {
		case Document_format_HTML:
			context.srcDocumentType = NSHTMLTextDocumentType;
			break;
		case Document_format_RTF:
			context.srcDocumentType = NSRTFTextDocumentType;
			break;					
		case Document_format_DOC:
			context.srcDocumentType = NSDocFormatTextDocumentType;
			break;	
		case Document_format_DOCX:
			context.srcDocumentType = NSOfficeOpenXMLTextDocumentType;
			break;	
		case Document_format_ODT:
			context.srcDocumentType = NSOpenDocumentTextDocumentType;
			break;				
		case Document_format_WORDML:
			context.srcDocumentType = NSWordMLTextDocumentType;
			break;		
		default:// Document_format_TXT:
			context.srcDocumentType = NSPlainTextDocumentType;
			break;					
	}	
	
	context.options = [[NSMutableDictionary alloc]initWithObjects:[NSArray arrayWithObject:context.srcDocumentType] 
														  forKeys:[NSArray arrayWithObject:NSDocumentTypeDocumentOption]]; 
	
	[context.options setValue:[NSNumber numberWithFloat:60.0f] 
						forKey:NSTimeoutDocumentOption];
	
	NSString *baseUrlString = Param4.copyUTF16String();
	NSURL *baseUrl = [[NSURL alloc]initWithString:baseUrlString];
	[baseUrlString release];
	
	if(baseUrl){
		[context.options setValue:baseUrl forKey:NSBaseURLDocumentOption];	
		[baseUrl release];
	}

	switch (Param3.getIntValue()) {
		case Document_format_HTML:
			context.dstDocumentType = NSHTMLTextDocumentType;
			break;
		case Document_format_RTF:
			context.dstDocumentType = NSRTFTextDocumentType;
			break;					
		case Document_format_DOC:
			context.dstDocumentType = NSDocFormatTextDocumentType;
			break;	
		case Document_format_DOCX:
			context.dstDocumentType = NSOfficeOpenXMLTextDocumentType;
			break;	
		case Document_format_ODT:
			context.dstDocumentType = NSOpenDocumentTextDocumentType;
			break;				
		case Document_format_WORDML:
			context.dstDocumentType = NSWordMLTextDocumentType;
			break;		
		default:// Document_format_TXT:
			context.dstDocumentType = NSPlainTextDocumentType;
			break;					
	}		
	
	context.attributes = [[NSMutableDictionary alloc]initWithObjects:[NSArray arrayWithObject:context.dstDocumentType] 
															 forKeys:[NSArray arrayWithObject:NSDocumentTypeDocumentAttribute]]; 	
	
	parseData(&context, returnValue);

	[context.attributes release];
	[context.options release];
	[context.data release];
	
	returnValue.setReturn(pResult);
}

void SET_ENVIRONMENT_VARIABLE(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT Param1;
	C_TEXT Param2;

	Param1.fromParamAtIndex(pParams, 1);
	Param2.fromParamAtIndex(pParams, 2);

    CUTF8String name, value;
    Param1.copyUTF8String(&name);
    Param2.copyUTF8String(&value);

	setenv((const char *)name.c_str(), (const char *)value.c_str(), 1);
}

void Get_environment_variable(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT Param1;
	C_TEXT returnValue;

	Param1.fromParamAtIndex(pParams, 1);

    CUTF8String name;
    Param1.copyUTF8String(&name);
    
	CUTF8String value((const uint8_t *)getenv((const char *) name.c_str()));
    
    returnValue.setUTF8String(&value);
	returnValue.setReturn(pResult);
}

