/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Document-Converter.h
 #	source generated by 4D Plugin Wizard
 #	Project : Document Converter
 #	author : miyako
 #	2020/09/04
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_DOCUMENT_CONVERTER_H
#define PLUGIN_DOCUMENT_CONVERTER_H

#include "4DPluginAPI.h"

#include "4DPlugin-JSON.h"

#include "C_TEXT.h"

#pragma mark -

#define Document_format_TXT 0
#define Document_format_RTF 1
#define Document_format_RTFD 2
#define Document_format_HTML 3
#define Document_format_DOC 4
#define Document_format_DOCX 5
#define Document_format_ODT 6
#define Document_format_WORDML 7
#define Document_format_WEBARCHIVE 8

typedef struct
{
    NSData *src;
    NSData *dst;
    NSDictionary *src_options;
    NSDictionary *dst_options;
} ConverterContext;

void Convert_document(PA_PluginParameters params);

#endif /* PLUGIN_DOCUMENT_CONVERTER_H */
