/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Document Converter
 #	author : miyako
 #	2014/08/09
 #
 # --------------------------------------------------------------------------------*/



// --- Document Converter
void Convert_document(sLONG_PTR *pResult, PackagePtr pParams);

#define Document_format_TXT 0
#define Document_format_RTF 1
//#define Document_format_RTFD 2
#define Document_format_HTML 3
#define Document_format_DOC 4
#define Document_format_DOCX 5
#define Document_format_ODT 6
#define Document_format_WORDML 7
//#define Document_format_WEBARCHIVE 8